### ISSUE TITLE
Bad config file

### ISSUE THREAD

**Issue by CTRQuko** [tajemniktv/TajsGraph#5] opened 2024-10-16 13:43 UTC
Hello, I have a rig with a 4090 and a 7800x3d. I expected that with your configuration, the graphics would look spectacular, but I've found that the shadow draw distance is too close, Lumen is nonexistent, and there are no reflections on surfaces. I hope to help you find a configuration for high-performance systems with RTX cards.  I deleted the default .ini file to reinstall your mod, but the results are exactly the same

Check out the videos I left as examples:

Your config
https://youtu.be/Ln6Ph4SoJUM

Default ultra config:

https://youtu.be/Y-JlgFGSH4U

If you notice, the shadow draw distance with your configuration is applied too close, whereas in the default configuration, the shadow already exists and is projected correctly.

the only mod that modifies the use of graphics are https://ficsit.app/mod/FrameGen and https://ficsit.app/mod/BetterGrass, 
The other mods I use only control day and night cycles.

**Comment by tajemniktv** [comment] 2024-10-16 14:33
Hi, thanks for reporting this!
I can confirm the issue with the shadows - As I was uploading the mod yesterday, I was too tired to include documentation or properly explain things on the mod page.

Currently (I'm not exactly sure why), VSM has to be re-enabled in the game, via console command: 
```
r.Shadow.Virtual.Enable 1
```
I will be working on either a fix or a reasonable workaround for this. 

What worries me the most, is you said that the Lumen is nonexistent and reflections aren't working properly...
I have worked on tweaking it manually before and created a [STEAM GUIDE](https://steamcommunity.com/sharedfiles/filedetails/?id=3338551101) in the process - there's a "photos" section, where you can check how exactly (or similiar-ish, gallery isn't updated regularly) the visual quality should look like. 

I could see FrameGen mod being a culprit here, the author did not share the source code for it, so I can't tell what exactly it does, but I will try to study it eitherway. BetterGrass *should* be fine (I also do tweak grass density scale [2.5], but as you can tell, for now there aren't any in-game settings)

Although please, don't expect **_really_** spectacular graphics - I'm rocking an RX5700XT combined with Ryzen5 3600 and I mostly tweak things with having similar hardware in mind (Without testing things myself, seeing it and being able to tweak it on the spot, it's kinda hard)
But that's why I also plan on adding customization (Maybe via a dedicated UI along with vanilla game Video settings). I'm a complete noob when it comes to modding, I barely started my journey here, so please keep that in mind;p


So yeah, for shadows I can see how that's happening, but with other things you mentioned - I will have to look into this

Again, thanks for reporting!

**Comment by tajemniktv** [comment] 2024-10-16 15:07
I couldn't get the FrameGenMod code, so I can't really tell what it's doing under the hood, but I'd be surprised if it would be the cause. Although I'd suggest trying without it first. (wait, I could actually try *with* it, imma do it)

Could you make sure you have the TajsGraph installed properly (does it show up in "Mods" in game?)
If so, please open console command (~) and type 
```
r.MeshStreaming
```
What did it say?

Unless lack of shadow causes all of this to happen, in that case... damn, gotta make up a solution quickly

**Comment by tajemniktv** [comment] 2024-10-16 15:14
Hm... Indeed there could be some issues with the "in-dev" tweaks I provided in the mod only (they aren't up in the guide yet). 

Yeah I can clearly see some issues with them. I will post a fix ASAP, that should fix Lumen not working properly. If there are gonna pop more issues, I will rollback to 0.7t version of tweaks

**Comment by tajemniktv** [comment] 2024-10-16 15:17
Dammit, another issue I forgot about earlier...

This command also has to be put on every start of a session. I will try to come up with a fix for it in todays evening. But for now, the workaround is to put also this
```
r.AOGlobalDistanceField.FastCameraMode 0
```
in your console command at the game startup. Dammit:(

**Comment by tajemniktv** [comment] 2024-10-16 15:39
Update is out, Lumen should be fixed. 
Please read the new description and remember to use the two commands provided there
https://ficsit.app/mod/TajsGraph

Let me know if that fixes it for you

**Comment by CTRQuko** [comment] 2024-10-16 17:30
so, following what you indicate in the description of the mod I have made this video for you:

https://youtu.be/lwvRvyRJ-nk


the performance is weird, it is not stable at all but looks spectacular

**Comment by tajemniktv** [comment] 2024-10-16 17:46
Thank you for that video, I really love your testing place! (Will definitely be stealing that idea :p)

Performance-wise, you could try setting Global Illumination quality to Medium in games Video settings. That shouldn't impact visual quality too much and all the tweaks from the mod should be preserved. You just gotta try it on your own, to see how that changes stuff. As I will be working further on the mod, I'm hoping to fine-tune it, so it balances quality and performance better. 

I'm actually working right now on a workaround for the need to use commands on every start. I could even possibly have it out later today, but we will see

Thanks again for reporting this, I don't know how I missed that Lumen isn't working properly. I will be closing this exact issue now, but I will open another one for the console thing. 
If you encounter other problems, don't hesitate to report them!

Cheers and enjoy better(ish) graphics!:D

**Comment by tajemniktv** [comment] 2024-10-16 17:47
Fixed in https://github.com/tajemniktv/TajsGraph/commit/7d553a43ee699b3d4df2977546ca75cb149667d1

**Closed by tajemniktv** 2024-10-16 17:46 UTC
Labels: Bug
