### ISSUE TITLE
Add a config screen for everything the mod adds and changes

### ISSUE THREAD

**Issue by Delfite** [tajemniktv/TajsGraph#20] opened 2024-10-20 01:10 UTC
Pretty self-explanatory. Add a config screen that allows us to enable and disable specific tweaks the mod makes, since not all of them provide any noticeable changes until they cause your FPS to tank for seemingly no reason. This is especially an issue with the shadows cast by conveyor belts and looking in the direction of even the most moderate amount of foliage despite both the Render Distance and Quality being set to Low.

**Comment by tajemniktv** [comment] 2024-10-20 11:42
Duplicate of https://github.com/tajemniktv/TajsGraph/issues/8

**Closed by tajemniktv** 2024-10-20 11:42 UTC
Labels: Duplicate

**Comment by tajemniktv** [comment] 2024-10-20 12:34
First thing I'm gonna add as config option (without a dedicated UI as planned) will be opting out of VSMs. I did prepare a config setting for it already but didn't make it work yet (and I forgot that I did that and pushed a version with broken config as a live version) I will work on it today hopefully and wil try to mqke it work
